name: Scheduled Python Script

on:
  schedule:
    - cron: '30 4,14 * * *'  # Runs at 9:30 AM and 8:30 PM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow
          pip install -r requirements.txt  # Adjust if you have dependencies

      - name: Run script
        run: python temp.py  # Replace with your script name
